language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-23

  licenses:
   - 'android-sdk-license-.+'

script:
  - android list target
  - ./gradlew test
